### ISSUE TITLE
I have some problem when passing from an activity to another.

### ISSUE THREAD

**Issue by imtoori** [AnirudhLoya/Kotlin-Android-Permissions-DeviceInfo#1]
The app crashes and I don't know why. Now I use another library and it works fine

**Comment by christophrrb** [comment]
@Salvatore-Giordano what library do you use?

**Comment by imtoori** [comment]
Sorry, but I don't remember, it was a little project and I abandoned it.
But I use your library in one of my apps and it works very well (it has only one activity).
I think I can close this issue, sorry for replying so late.
